# Generated by Django 2.2.4 on 2019-08-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_upload_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Content')),
                ('digest', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('application/vnd.docker.container.image.v1+json', 'application/vnd.docker.container.image.v1+json'), ('application/vnd.docker.image.rootfs.diff.tar.gzip', 'application/vnd.docker.image.rootfs.diff.tar.gzip'), ('application/vnd.docker.image.rootfs.foreign.diff.tar.gzip', 'application/vnd.docker.image.rootfs.foreign.diff.tar.gzip')], max_length=80)),
            ],
            options={
                'unique_together': {('digest',)},
            },
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='BlobManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DockerRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Remote')),
                ('upstream_name', models.CharField(db_index=True, max_length=255)),
                ('include_foreign_layers', models.BooleanField(default=False)),
                ('whitelist_tags', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.remote',),
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Content')),
                ('digest', models.CharField(max_length=255)),
                ('schema_version', models.IntegerField()),
                ('media_type', models.CharField(choices=[('application/vnd.docker.distribution.manifest.v1+json', 'application/vnd.docker.distribution.manifest.v1+json'), ('application/vnd.docker.distribution.manifest.v2+json', 'application/vnd.docker.distribution.manifest.v2+json'), ('application/vnd.docker.distribution.manifest.list.v2+json', 'application/vnd.docker.distribution.manifest.list.v2+json')], max_length=60)),
                ('blobs', models.ManyToManyField(through='docker.BlobManifest', to='docker.Blob')),
                ('config_blob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_blob', to='docker.Blob')),
            ],
            bases=('core.content',),
        ),
        migrations.CreateModel(
            name='ManifestListManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('os_version', models.CharField(blank=True, default='', max_length=255)),
                ('os_features', models.TextField(blank=True, default='')),
                ('features', models.TextField(blank=True, default='')),
                ('variant', models.CharField(blank=True, default='', max_length=255)),
                ('image_manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_manifests', to='docker.Manifest')),
                ('manifest_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_lists', to='docker.Manifest')),
            ],
            options={
                'unique_together': {('image_manifest', 'manifest_list')},
            },
        ),
        migrations.AddField(
            model_name='manifest',
            name='listed_manifests',
            field=models.ManyToManyField(through='docker.ManifestListManifest', to='docker.Manifest'),
        ),
        migrations.CreateModel(
            name='DockerDistribution',
            fields=[
                ('basedistribution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseDistribution')),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Repository')),
                ('repository_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.RepositoryVersion')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.basedistribution',),
        ),
        migrations.AddField(
            model_name='blobmanifest',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blob_manifests', to='docker.Manifest'),
        ),
        migrations.AddField(
            model_name='blobmanifest',
            name='manifest_blob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_blobs', to='docker.Blob'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Content')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('tagged_manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagged_manifests', to='docker.Manifest')),
            ],
            options={
                'unique_together': {('name', 'tagged_manifest')},
            },
            bases=('core.content',),
        ),
        migrations.AlterUniqueTogether(
            name='manifest',
            unique_together={('digest',)},
        ),
        migrations.AlterUniqueTogether(
            name='blobmanifest',
            unique_together={('manifest', 'manifest_blob')},
        ),
    ]
