# Generated by Django 2.0.6 on 2018-06-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.content',),
        ),
        migrations.CreateModel(
            name='DockerPublisher',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Publisher')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.publisher',),
        ),
        migrations.CreateModel(
            name='DockerRemote',
            fields=[
                ('remote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Remote')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.remote',),
        ),
    ]
