# Generated by Django 2.2.4 on 2019-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestlistmanifest',
            name='os_version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestlistmanifest',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
